name: snowflake-demo
channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - nodefaults
dependencies:
  - python=3.10
  - snowflake-snowpark-python
  - pip
  - openssl=1.1.1
  - pip:
    # Snowflake
    - snowflake-cli-labs
<<<<<<< HEAD
=======
    - snowflake-snowpark-python
    - snowflake
>>>>>>> 39e28f8bcaa90f38fcabe2ecb1fd5a8d58e24dcb
